# SPDX-License-Identifier: Apache-2.0
#

# Base compose files for:

# orderer.treeconnector.com
# peer0.doctors.treeconnector.com
# peer0.treats.treeconnector.com
# peer0.condomngs.treeconnector.com
# peer0.individuals.treeconnector.com


version: '2'  # v3 does not support 'extends' yet

services:

  orderer.treeconnector.com:  # There can be multiple orderers
    extends:
      file: orderer-base.yaml
      service: orderer-base
    container_name: orderer.treeconnector.com
    hostname: orderer.treeconnector.com
    ports:
      - "7050:7050"
    volumes:
    - ./cli/channel-artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./cli/crypto-config/ordererOrganizations/treeconnector.com/orderers/orderer.treeconnector.com/msp:/var/hyperledger/orderer/msp
    - ./cli/crypto-config/ordererOrganizations/treeconnector.com/orderers/orderer.treeconnector.com/tls/:/var/hyperledger/orderer/tls
    command: orderer start

  peer0.doctors.treeconnector.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer0.doctors.treeconnector.com
    hostname: peer0.doctors.treeconnector.com
    environment:
      - CORE_PEER_ID=peer0.doctors.treeconnector.com
      - CORE_PEER_ADDRESS=peer0.doctors.treeconnector.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.doctors.treeconnector.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.doctors.treeconnector.com:7051
      - CORE_PEER_LOCALMSPID=doctorsMSP
    volumes:
        - ./cli/crypto-config/peerOrganizations/doctors.treeconnector.com/peers/peer0.doctors.treeconnector.com/msp:/etc/hyperledger/fabric/msp
        - ./cli/crypto-config/peerOrganizations/doctors.treeconnector.com/peers/peer0.doctors.treeconnector.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    command: peer node start

  peer0.treats.treeconnector.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer0.treats.treeconnector.com
    hostname: peer0.treats.treeconnector.com
    environment:
      - CORE_PEER_ID=peer0.treats.treeconnector.com
      - CORE_PEER_ADDRESS=peer0.treats.treeconnector.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.treats.treeconnector.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.treats.treeconnector.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.doctors.treeconnector.com:7051
      - CORE_PEER_LOCALMSPID=doctorsMSP
    volumes:
        - ./cli/crypto-config/peerOrganizations/doctors.treeconnector.com/peers/peer0.treats.treeconnector.com/msp:/etc/hyperledger/fabric/msp
        - ./cli/crypto-config/peerOrganizations/doctors.treeconnector.com/peers/peer0.treats.treeconnector.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053
    command: peer node start

  peer0.condomngs.treeconnector.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer0.condomngs.treeconnector.com
    hostname: peer0.condomngs.treeconnector.com
    environment:
      - CORE_PEER_ID=peer0.condomngs.treeconnector.com
      - CORE_PEER_ADDRESS=peer0.condomngs.treeconnector.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.condomngs.treeconnector.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.condomngs.treeconnector.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.condomngs.treeconnector.com:7051
      - CORE_PEER_LOCALMSPID=condomngsMSP
    volumes:
        - ./cli/crypto-config/peerOrganizations/condomngs.treeconnector.com/peers/peer0.condomngs.treeconnector.com/msp:/etc/hyperledger/fabric/msp
        - ./cli/crypto-config/peerOrganizations/condomngs.treeconnector.com/peers/peer0.condomngs.treeconnector.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
    command: peer node start

  peer0.individuals.treeconnector.com:
    extends:
      file: peer-base.yaml
      service: peer-base
    container_name: peer0.individuals.treeconnector.com
    hostname: peer0.individuals.treeconnector.com
    environment:
      - CORE_PEER_ID=peer0.individuals.treeconnector.com
      - CORE_PEER_ADDRESS=peer0.individuals.treeconnector.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.individuals.treeconnector.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.individuals.treeconnector.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.individuals.treeconnector.com:7051
      - CORE_PEER_LOCALMSPID=treatsMSP
    volumes:
        - ./cli/crypto-config/peerOrganizations/individuals.treeconnector.com/peers/peer0.individuals.treeconnector.com/msp:/etc/hyperledger/fabric/msp
        - ./cli/crypto-config/peerOrganizations/individuals.treeconnector.com/peers/peer0.individuals.treeconnector.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053
    command: peer node start


  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.doctors.treeconnector.com:7051
      - CORE_PEER_LOCALMSPID=doctorsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/doctors.treeconnector.com/peers/peer0.doctors.treeconnector.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/doctors.treeconnector.com/peers/peer0.doctors.treeconnector.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/doctors.treeconnector.com/peers/peer0.doctors.treeconnector.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/doctors.treeconnector.com/users/Admin@doctors.treeconnector.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./cli/examples/chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./cli/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./cli/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.treeconnector.com
      - peer0.doctors.treeconnector.com
      - peer0.treats.treeconnector.com
      - peer0.condomngs.treeconnector.com
      - peer0.individuals.treeconnector.com
